In [ ]:
# data must be homogeneous
# these data types must be one og the data types (dtypes) provided by numpy
# some important data types are: float64, int64, bool(8 bit)
# default dtype is float64


In [6]:
import numpy as np

a = np.zeros(3)
a

array([0., 0., 0.])

In [7]:
z = np.zeros(10)

In [8]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
z.shape

(10,)

In [16]:
z.shape = (5,2)
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
z.shape

(5, 2)

In [18]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [15]:
c = np.empty(4)
c

array([1.04725875e-311, 9.83092866e-315, 9.88131292e-324,             nan])

In [21]:
d = np.linspace(2,10,8) #from 2 to 10 with 8 elemenst in between including 2 and 10
d

array([ 2.        ,  3.14285714,  4.28571429,  5.42857143,  6.57142857,
        7.71428571,  8.85714286, 10.        ])

In [22]:
a = np.array([10,21])
a

array([10, 21])

In [23]:
a.shape

(2,)

In [24]:
?a.shape

In [35]:
z = np.random.randint(10,size=5) #the last element is not taken in account
z

array([2, 2, 9, 1, 4])

In [36]:
z[0]

2

In [78]:
a = np.random.rand(0,3)
a

array([], shape=(0, 3), dtype=float64)

In [63]:
a = np.random.uniform(0,1,size=2)
a

array([0.07138862, 0.05451985])

In [64]:
type(a)

numpy.ndarray

In [66]:
# to create identity matrix np.identity or np.eye
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
#  is keyword is used to check if it is equal
a=2
a is 2

True

In [73]:
a = np.linspace(1,10,10)
a
a is np.asarray(a) # does not make a new copy of  dta already in numpy array

True

In [76]:
a is np.array(a) # makes a new copy of data - unnecessarily

False

In [79]:
# ARRAY INDEXING

In [122]:
z = np.linspace(1,10,10,dtype=int)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
z[0]

1

In [124]:
z[0:3]

array([1, 2, 3])

In [125]:
z[-2]

9

In [126]:
z[4:]

array([ 5,  6,  7,  8,  9, 10])

In [127]:
indices=np.array([1,3,5,7,9])
z[indices]

array([ 2,  4,  6,  8, 10])

In [128]:
b = np.array([0,1,0,1,61,0,1,5,0,1],dtype=bool)
b

array([False,  True, False,  True,  True, False,  True,  True, False,
        True])

In [129]:
z[b]

array([ 2,  4,  5,  7,  8, 10])

In [130]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
z.sort()
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
import random

In [133]:
random.shuffle(z)
z

array([ 6,  2,  8,  3,  1,  9,  4, 10,  7,  5])

In [134]:
z.sort()
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
z.sum()

55

In [136]:
z.mean()

5.5

In [137]:
z.max()

10

In [138]:
z.argmax() # return index of max element in array

9

In [139]:
z.cumsum() # cumulative sum of elements of z

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [140]:
z.cumprod() #cumulative product of elements of z

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [141]:
z.var() # variance

8.25

In [142]:
z.std() # standard deviation

2.8722813232690143

In [146]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [147]:
a.T

array([[1, 3],
       [2, 4]])

In [155]:
a = np.linspace(-1,2,5,dtype=int)
a

array([-1,  0,  0,  1,  2])

In [156]:
np.sum(a)

2

In [157]:
np.sort(a)

array([-1,  0,  0,  1,  2])

In [158]:
np.mean(a)

0.4

In [ ]:
# AIRTHMETIC OPERATIONS

In [166]:
a = np.array([1,8,5,4,9])
b= np.array([7,6,5,9,2])

In [167]:
a+b

array([ 8, 14, 10, 13, 11])

In [168]:
a*b

array([ 7, 48, 25, 36, 18])

In [169]:
a+10

array([11, 18, 15, 14, 19])

In [171]:
a*10

array([10, 80, 50, 40, 90])

In [172]:
A = np.ones((2,2))
B = np.ones((2,2))

In [174]:
A+B

array([[2., 2.],
       [2., 2.]])

In [175]:
A+10

array([[11., 11.],
       [11., 11.]])

In [176]:
A*10

array([[10., 10.],
       [10., 10.]])

In [177]:
A*B # THIS IS NOT MATRIX MULTIPLICATION IT IS SIMPLE ELEMENT-WISE PRODUCT

array([[1., 1.],
       [1., 1.]])

In [183]:
A@B # @ Symbols does matrix multiplication

array([[2., 2.],
       [2., 2.]])

In [184]:
# NUMPY ARRAYS ARE MUTABLE

In [186]:
a = np.array([2,3,45,6])
a

array([ 2,  3, 45,  6])

In [188]:
a[-2]=0
a

array([2, 3, 0, 6])

In [201]:
n = np.random.randn(4,4)
n

array([[-0.11972507, -1.11693735, -0.92010216, -0.66103782],
       [ 0.25302857, -2.34098761,  1.76866333,  0.52859921],
       [ 0.48598815,  1.42477482,  2.07356372,  2.67258474],
       [ 0.13340052, -0.88163298,  0.35047685, -0.80525387]])

In [202]:
e = np.linspace(5,1,5)
e

array([5., 4., 3., 2., 1.])

In [205]:
f=e
f[2]=0
e
# WE CHANGED A BY CHANGING B
# The name b is bound to a and becomes just another reference to the array.
# Hence, it has equal rights to make changes to that array
# This is in fact the most sensible default behavior!
# It means that we pass around only pointers to data, rather than making copies
# Making copies is expensive in terms of both speed and memory

array([5., 4., 0., 2., 1.])

In [207]:
g = np.copy(e)
g
#  now g is DEEP COPY or we may call it INDEPENDENT COPY

array([5., 4., 0., 2., 1.])

In [209]:
g[:]=1
g

array([1., 1., 1., 1., 1.])